{
    gStyle->SetLabelSize(0.05, "x");
    gStyle->SetLabelSize(0.05, "y");
    gStyle->SetTitleSize(0.05, "x");
    gStyle->SetTitleSize(0.05, "y");
    gStyle->SetLineWidth(1);
    gStyle->SetPadTopMargin(0.15);
    gStyle->SetPadBottomMargin(0.13);
    gStyle->SetPadRightMargin(0.13);
    gStyle->SetPadLeftMargin(0.13);
    const int canvasWidth = 1200, canvasHeight = 800;
    TCanvas *canv1 = new TCanvas("c1", "Spot Dose", canvasWidth, canvasHeight);
    TGraph *gr1 = new TGraphErrors("result151-PtnE.4.c_y_spotdose_diff.csv", "%*lg,%lg,%*lg,%lg");
    // canv1->SetGrid(0, 1);
    gr1->Draw("AP");
    gr1->GetYaxis()->SetNdivisions(505);
    gr1->GetXaxis()->SetNdivisions(505);
    gr1->SetMarkerStyle(8);
    gr1->SetMarkerSize(1);
    gr1->GetYaxis()->SetRangeUser(0.5, 1.5);
    gr1->GetXaxis()->SetTitle("Dose (mGy)");
    gr1->GetYaxis()->SetTitle("#Deltadose/dose");
    TF1 f1("func1", "TMath::Sqrt((1/x/x+0.02^2+0.006^2))+1", 0, 300);
    f1.SetLineColor(kGray);
    f1.SetLineStyle(2);
    f1.Draw("SAME");
    TF1 f2("func2", "-TMath::Sqrt((1/x/x+0.02^2+0.006^2))+1", 0, 300);
    f2.SetLineColor(kGray);
    f2.SetLineStyle(2);
    f2.Draw("SAME");
}